name: Generate JWT and Upload Logs to BigQuery

on:
  workflow_dispatch:  # 手動実行を許可

permissions:
  id-token: write
  contents: read

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: miurak
      BQ_DATASET: test
      BQ_TABLE: git_audit2

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/55684806562/locations/global/workloadIdentityPools/gha-pool-git-export/providers/github'
          service_account: 'git-audit-gha-sa@miurak.iam.gserviceaccount.com'

      - name: Clear old virtual environment
        run: |
          rm -rf venv

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install google-cloud-bigquery requests PyJWT

      - name: Generate JWT token
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          . venv/bin/activate
          python3 app/generate_jwt.py > jwt_token.txt

      - name: Fetch audit logs using JWT token
        run: |
          . venv/bin/activate
          jwt_token=$(cat jwt_token.txt)
          response=$(curl -H "Authorization: Bearer $jwt_token" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/orgs/miurak-test/audit-log")

          mkdir -p app
          echo "$response" > app/audit_logs.json

      - name: Run script to upload logs to BigQuery
        run: |
          . venv/bin/activate
          python3 app/script2.py
