name: Fetch and Upload GitHub Audit Logs to BigQuery

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行
  workflow_dispatch:  # 手動実行も可能に

permissions:
  id-token: write  
  contents: read  

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: miurak
      BQ_DATASET: test
      BQ_TABLE: git_audit2

    steps:
      - uses: actions/checkout@v4  

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/55684806562/locations/global/workloadIdentityPools/gha-pool-git-export/providers/github'
          service_account: 'git-audit-gha-sa@miurak.iam.gserviceaccount.com'

      - name: Clear old virtual environment
        run: |
          rm -rf venv

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install google-cloud-bigquery requests PyJWT

      - name: Generate JWT Token
        run: |
          . venv/bin/activate
          python3 app/generate_jwt.py > jwt_token.txt

      - name: Display JWT Token for Debugging
        run: |
          cat jwt_token.txt

      - name: Save Private Key to File (Optional Debugging)
        run: |
          echo "${{ secrets.APP_PRIVATE_KEY }}" > app/private-key.pem
