name: Fetch and Upload GitHub Audit Logs to BigQuery

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行
  workflow_dispatch:  # 手動実行も可能に

permissions:
  id-token: write
  contents: read

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: miurak
      BQ_DATASET: test
      BQ_TABLE: git_audit2

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/55684806562/locations/global/workloadIdentityPools/gha-pool-git-export/providers/github'
          service_account: 'git-audit-gha-sa@miurak.iam.gserviceaccount.com'
          create_credentials_file: true
          export_environment_variables: true

      - name: Clear old virtual environment
        run: |
          rm -rf venv

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install google-cloud-bigquery requests PyJWT

      # GitHub Appsトークンを生成
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # GitHubの監査ログを取得し、保存
      - name: Fetch GitHub Audit Logs
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
        run: |
          . venv/bin/activate
          response=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/orgs/miurak-test/audit-log")
          echo "$response" > app/audit_logs.json

      # 監査ログをBigQueryにアップロード
      - name: Upload logs to BigQuery
        run: |
          . venv/bin/activate
          python3 app/script2.py
