name: Fetch and Upload GitHub Audit Logs to BigQuery

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行
  workflow_dispatch:  # 手動実行も可能に

permissions:
  id-token: write  # IDトークンの書き込み権限を付与
  contents: read   # リポジトリの内容に対する読み取りアクセス

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    env:
      GCP_PROJECT_ID: miurak  # GCPプロジェクトID
      BQ_DATASET: test         # BigQueryデータセット名
      BQ_TABLE: git_audit2     # BigQueryテーブル名

    steps:
      # リポジトリの内容をチェックアウトする（ソースコードを取得）
      - uses: actions/checkout@v4  # 最新バージョンを使用

      # Google Cloudに認証するための設定（Workload Identity Federation）
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'  # Node.js 20対応の最新バージョン
        with:
          workload_identity_provider: 'projects/55684806562/locations/global/workloadIdentityPools/gha-pool-git-export/providers/github'
          service_account: 'git-audit-gha-sa@miurak.iam.gserviceaccount.com'
          create_credentials_file: true
          export_environment_variables: true

      # 仮想環境をセットアップし、必要なライブラリをインストール
      - name: Set up Python environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install google-cloud-bigquery requests

      # GitHub AppのJWTトークンを生成
      - name: Generate GitHub App JWT Token
        run: |
          . venv/bin/activate
          python3 app/generate_jwt.py > jwt_token.txt

      # 監査ログを取得し、BigQueryにアップロード
      - name: Upload logs to BigQuery
        run: |
          . venv/bin/activate
          python3 app/script2.py
