name: Fetch and Upload GitHub Audit Logs to BigQuery

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行
  workflow_dispatch:  # 手動実行も可能に

permissions:
  contents: write  # リポジトリのコンテンツへの書き込み権限

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    env:
      GCP_PROJECT_ID: miurak  # GCPプロジェクトID
      BQ_DATASET: test         # BigQueryデータセット名
      BQ_TABLE: git_audit2      # BigQueryテーブル名

    steps:
      # リポジトリの内容をチェックアウトする（ソースコードを取得）
      - uses: actions/checkout@v4  # 最新バージョンを使用

      # Google Cloudに認証するための設定を実行（Workload Identity Federationを使用）
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'  # Node.js 20対応の最新バージョン
        with:
          workload_identity_provider: 'projects/55684806562/locations/global/workloadIdentityPools/gha-pool-git-export/providers/github'
          service_account: 'git-audit-gha-sa@miurak.iam.gserviceaccount.com'  # 使用するサービスアカウント

      # GitHub Appsトークンを生成
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}  # App IDをSecretsから取得
          private_key: ${{ secrets.APP_PRIVATE_KEY }}  # 秘密鍵を取得

      # Python環境をセットアップ
      - name: Set up Python environment
        run: |
          python3 -m venv venv  # 仮想環境を作成
          . venv/bin/activate  # 仮想環境を有効化
          pip install --upgrade pip  # pipを最新に更新
          pip install google-cloud-bigquery requests PyJWT  # 必要なライブラリをインストール

      # GitHub APIから監査ログを取得
      - name: Fetch audit logs from GitHub
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}  # 生成したトークンを使用
        run: |
          . venv/bin/activate  # 仮想環境を有効化
          current_time=$(date --utc --iso-8601=seconds)  # 現在のUTC時刻を取得
          echo "$current_time" > artifacts/last_run_timestamp.txt  # タイムスタンプを保存

          # GitHub APIから監査ログを取得
          response=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/orgs/miurak-test/audit-log")

          # ログを`app`ディレクトリに保存
          mkdir -p app  # ディレクトリを作成
          echo "$response" > app/audit_logs.json  # JSONファイルに保存

      # BigQueryにログをアップロード
      - name: Upload logs to BigQuery
        run: |
          . venv/bin/activate  # 仮想環境を有効化
          python3 app/script2.py  # スクリプトを実行
