name: Fetch and Upload GitHub Audit Logs to BigQuery

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時に実行
  workflow_dispatch:  # 手動実行も可能に

permissions:
  id-token: write  # Google Cloudの認証用トークンの発行を許可
  contents: read   # リポジトリの内容に読み取りアクセスを付与

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    env:
      GCP_PROJECT_ID: miurak  # GCPプロジェクトID
      BQ_DATASET: test         # BigQueryデータセット名
      BQ_TABLE: git_audit2     # BigQueryテーブル名

    steps:
      # リポジトリの内容をチェックアウトする（ソースコードを取得）
      - uses: actions/checkout@v4  # 最新バージョンを使用

      # Google Cloudに認証するための設定を実行（Workload Identity Federationを使用）
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'  # Node.js 20対応の最新バージョンを使用
        with:
          workload_identity_provider: 'projects/55684806562/locations/global/workloadIdentityPools/gha-pool-git-export/providers/github'
          service_account: 'git-audit-gha-sa@miurak.iam.gserviceaccount.com'  # 使用するサービスアカウント

      # 古い仮想環境（venv）が存在する場合は削除
      - name: Clear old virtual environment
        run: |
          rm -rf venv

      # Pythonの仮想環境をセットアップし、必要なライブラリをインストール
      - name: Set up Python environment
        run: |
          python3 -m venv venv  # 仮想環境を作成
          . venv/bin/activate  # 仮想環境を有効化
          pip install --upgrade pip  # pipを最新バージョンに更新
          pip install google-cloud-bigquery requests pyjwt  # 必要なライブラリをインストール

      # JWTトークンを生成してファイルに保存
      - name: Generate JWT Token
        run: |
          . venv/bin/activate  # 仮想環境を有効化
          python3 app/generate_jwt.py > jwt_token.txt  # JWTトークン生成

      # GitHub APIを使用して監査ログを取得し、次回の実行に向けてタイムスタンプを更新
      - name: Fetch audit logs from GitHub
        env:
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}  # JWTトークンを使用
        run: |
          . venv/bin/activate  # 仮想環境を有効化
          current_time=$(date --utc --iso-8601=seconds)  # 現在のUTC時刻を取得
          echo "$current_time" > artifacts/last_run_timestamp.txt  # 新しいタイムスタンプを保存

          # GitHub APIから監査ログを取得
          response=$(curl -H "Authorization: Bearer $(cat jwt_token.txt)" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/app/installations/${{ secrets.APP_INSTALLATION_ID }}/access_tokens")

          echo "$response" > app/audit_logs.json  # 取得したログを保存

      # BigQueryにログをアップロードするPythonスクリプトを実行
      - name: Run script to upload logs to BigQuery
        run: |
          . venv/bin/activate  # 仮想環境を有効化
          python3 app/script2.py  # Pythonスクリプトを実行
